name: pybpod-api-env
dependencies:
  - python=3.6
  - numpy
  - sphinx>=1.5
  - pip:
      - python-dateutil
      - pyserial>=3.1.1
      - https://github.com/snide/sphinx_rtd_theme/archive/master.zip
      - https://bitbucket.org/fchampalimaud/logging-bootstrap/get/master.zip